name: fleischhygiene
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter_slider_drawer: ^2.0.0
  flutter:
    sdk: flutter
  http: ^0.13.3
  step_progress_indicator: ^1.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - asset/badges/
    - asset/certificates/
    - asset/icons/
    - asset/icons/SuFuIcon.png
    - asset/illustrations/
    - asset/images/
    - asset/images/Gefluegel.jpg
    - asset/images/WildTXT.png
    - asset/images/TrUSTXT.png
    - asset/images/BUTXT.png
    - asset/images/BeurteilungTXT.png
    - asset/images/GrundlagenTXT.jpg
    - asset/images/Vorbericht+SU.png
    - asset/images/SUFU1.jpg
    - asset/images/Fleischuntersuchung.jpg
    - asset/images/zusaetzliche US.jpg
    - asset/images/Fleischuntersuchung Rind 1.jpg
    - asset/images/Fleischuntersuchung Rind 2.jpg
    - asset/images/Fleischuntersuchung Rind 3.jpg
    - asset/images/FUjungeRinderTXT.jpg
    - asset/images/FUsonstigeRinderTXT.jpg
    - asset/images/FUjungeSchafeTXT.jpg
    - asset/images/FUsonstigeSchafeTXT.jpg
    - asset/images/FUEinhuferTXT.jpg
    - asset/images/GrundlagenTXT.jpg
    - asset/images/TransportfaehigkeitTXT.jpg
    - asset/images/TransportmittelTXT.jpg
    - asset/images/TransportpraxisTXT.jpg
    - asset/images/ZeitabstaendeTXT.jpg
    - asset/images/LangeBefoerderungTXT.jpg
    - asset/images/FUHausschweineTXT.jpg
    - asset/images/BetaeubenTXT.jpg
    - asset/images/Entbluten.jpg
    - asset/images/Enthaeuten.jpg
    - asset/images/BruehenTXT.jpg
    - asset/images/AusweidenTXT.jpg
    - asset/images/SpaltenTXT.jpg
    - asset/images/AusweidenFrame.jpg
    - asset/images/BetaeubenFrame.jpg
    - asset/images/BeurteilungFrame.jpg
    - asset/images/BruehenFrame.jpg
    - asset/images/BUHTFrame.jpg
    - asset/images/cloud-in-blue-sky.jpg
    - asset/images/EinhuferFrame.jpg
    - asset/images/EntblutenFrame.jpg
    - asset/images/EnthaeutenFrame.jpg
    - asset/images/FUFrame.jpg
    - asset/images/GefluegelFrame.jpg
    - asset/images/GrundlagenFrame.jpg
    - asset/images/HausschweineFrame.jpg
    - asset/images/JRinderFrame.jpg
    - asset/images/jSchafeFrame.jpg
    - asset/images/lBefoerderungFrame.jpg
    - asset/images/rd1.png
    - asset/images/rd2.png
    - asset/images/rd3.png
    - asset/images/rd4.png
    - asset/images/SpaltenFrame.jpg
    - asset/images/sRinderFrame.jpg
    - asset/images/sSchafeFrame.jpg
    - asset/images/sun-behind-cloud.jpg
    - asset/images/sun-clouds.jpg
    - asset/images/sun-with-clouds.jpg
    - asset/images/Teil1Frame.jpg
    - asset/images/Teil2Frame.jpg
    - asset/images/Teil 3_1Icon.jpg
    - asset/images/TPFrame.jpg
    - asset/images/TransportfaehigkeitFrame.jpg
    - asset/images/TransportmittelFrame.jpg
    - asset/images/TrUSFrame.jpg
    - asset/images/TSEFrame.jpg
    - asset/images/Uebersicht1.png
    - asset/images/Uebersicht2.png
    - asset/images/UebersichtFrame.jpg
    - asset/images/VorberichtFrame.jpg
    - asset/images/WildFrame.jpg
    - asset/images/ZeitabstaendeFrame.jpg
    - asset/images/zusUSFrame.jpg
    - asset/images/Uebersicht1_1Frame.jpg
    - asset/images/Uebersicht1_2Frame.jpg
    - asset/images/Point.jpg
    - asset/images/trophy.png
    - asset/logos/

